spring:
  application:
    name: adobe-challenge-1b
  datasource:
    url: jdbc:h2:file:./data/hackathon
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false  # Changed to false for production
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 500MB

server:
  port: 8080
  address: 0.0.0.0  # Bind to all interfaces for external access
  servlet:
    context-path: /
  compression:
    enabled: true  # Enable compression for better performance
  http2:
    enabled: true  # Enable HTTP/2 for Adobe PDF Embed API

app:
  file:
    storage:
      upload-dir: ./uploads
      max-size: 104857600 # 100MB
  analysis:
    enhanced:
      enabled: true
      max-sections-per-document: 5
      confidence-threshold: 0.7
      detailed-analysis: true
  pdf:
    processing:
      timeout: 300000
    max-pages: 500

    cors:
    allowed-origins: "http://localhost:3000,http://localhost:8080"
    allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
    allowed-headers: "*"

llm:
  provider: gemini
  model: gemini-2.5-flash
  api:
    timeout: 30000

adobe:
  pdf:
    client-id: "${ADOBE_CLIENT_ID:}"
    client-secret: "${ADOBE_CLIENT_SECRET:}"

logging:
  level:
    com.adobe.hackathon: INFO
    org.springframework.web: WARN  # Reduced logging